version: '3'
services: 
    rest-crud-mongodb-api:
        restart: always
        build: .
        ports:
            - '3000:3000'
        links:
            - db
    db:
        image: mongo:latest
        ports: 
            - '27017:27017'